apiVersion: v2
appVersion: "2.4.8"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.1.4
deprecated: false
description: An filesharer
home: https://github.com/alexander-lindner/go-fileshare
icon: https://truecharts.org/_static/img/appicons/heimdall.png
keywords:
  - go-fileshare
kubeVersion: '>=1.16.0-0'
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: fileshare
sources:
  - https://github.com/alexander-lindner/go-fileshare
type: application
version: 0.1.0
annotations:
  truecharts.org/catagories: |
    - organizers
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U